config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]
  ActiveAdmin.routes(self)
  root 'products#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_uniqueness_of :name, :case_sensitive => true

  has_and_belongs_to_many :products
  accepts_nested_attributes_for :products

  extend Searchable

  def self.q _q
    _q = validated_query(_q)
    return where(nil) unless _q

    select('categories.name, categories.id').where(id: joins(:products).where('products.name ILIKE ? OR categories.name ILIKE ?', "%#{_q}%", "%#{_q}%").limit(100).pluck(:id).uniq )
  end

  def self.root limit=nil
    unless limit.try(:to_i) and limit.try(:to_i) > 1
      limit = 20
    end

    where('categories.parent_id IS NULL').order('categories.name').limit(limit)
  end

  def self.total
    # Rails.cache.fetch("Category#total", expires_in: 12.hours) do
      self.select('id').count
    # end
  end
end

app/models/concerns/searchable.rb
module Searchable
  def validated_query q
    q = q.to_s.strip.scan(/\w+/).first
    return nil if q.blank?
    return nil if q.length < 2

    q = q.singularize

    q = q[0..5] if q.length>7

    q
  end

  def validated_pagination page, per_page
    if page.respond_to? :to_i
      page = page.to_i
    else
      page = 1
    end

    page = 1 if page < 1
    page = 100 if page > 100

    if per_page.respond_to? :to_i
      per_page = page.to_i
    else
      per_page = 100
    end

    per_page = 100 if per_page==0

    per_page = 20 if per_page < 20
    per_page = 100 if per_page > 100

    limit = per_page
    offset = ( (page-1) * per_page)
    offset = 0 if offset < 0

    [limit, offset]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_uniqueness_of :name, :case_sensitive => true

  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories

  extend Searchable

  def categories_name
    categories.select(' categories.name ').pluck(:name).join(', ')
  end

  def self.q _q, page=0, per_page=20
    _q = validated_query(_q)
    return where(nil) unless _q

    limit, offset = validated_pagination page, per_page

    joins(:categories).
      where('products.name ILIKE ? OR categories.name ILIKE ?', "%#{_q}%", "%#{_q}%").
      select(' products.id, products.name, products.price ').
      limit(limit).offset(offset)
  end

  def self.q_count _q
    _q = validated_query(_q)
    return 0 unless _q

    Rails.cache.fetch("Product#q_count:#{_q}", expires_in: 12.hours) do

      joins(:categories).
        where('products.name ILIKE ? OR categories.name ILIKE ?', "%#{_q}%", "%#{_q}%").
        select(' products.id ').
        count
    end
  end

  def self.sort sort_column='name', asc='ASC'
    sort_column = sort_column.to_s.strip
    asc = asc.to_s.strip

    sort_column = %w{name price}.include?(sort_column) ? sort_column : 'name'
    asc = %w{ASC DESC}.include?(asc) ? asc : 'ASC'

    reorder(" products.#{sort_column} #{asc}")
  end

  def self.total
    Rails.cache.fetch("Product#total", expires_in: 12.hours) do
      self.select('id').count
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :rails_ignore_chrome_head_followup

  def rails_ignore_chrome_head_followup
    head :ok and return if request.head?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base

  def index
    sql = Category.q(params[:q]).to_sql

    respond_to do |format|
      format.json { render json: { data: ActiveRecord::Base.connection.execute(sql), info: {
        resource: controller_name
      }}}
      
    end
  end

  def root
    @categoies.root
  end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

  def index
    count = 0#Product.q_count(params[:q])
    sql = Product.q(params[:q], params[:page], params[:per_page]).sort(params[:s]).to_sql

    # TBD pagination
    # TBD limit in query with min and max condition
    # TBD solr and posgres text search and lucene and %more comparisons
    # TBD API version
    # TBD api key or oauth2
    # TBD sorting
    # TBD keep one pre-search engine where a bot will search for frequent queries and their combination
    #     this is to keep frequest searches faster

    respond_to do |format|
      format.json { render json: { data: ActiveRecord::Base.connection.execute(sql), info: {
        resource: controller_name, count: count
      }}}
      
      format.any { render :index }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.parent_id %></td>
        <td><%= link_to 'Show', category %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @category.parent_id %>
</p>

<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>RMD | <%= @product.try(:name) %></title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Search Products</a></li>
          <li class="active pull-right"><a href="/admin" target="_blank">Admin</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
  <div id="spinner">
    <%= image_tag("spinner.gif") %>
  </div>
</body>
</html>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Page Content -->
<div class="container">

    <div class="row" style="border-bottom: 1px solid #eef; ">
        <div class="col-md-8" style="margin-left: auto; margin-right:auto; float:none;">
            <div class="row">
                <input data-search="products categories" name="q" placeholder="Search <%= Product.total %> products, <%= Category.total %> ategories, example bags" class="search col-md-11">
                <button class="search_button col-md-1" value="search"> <i data-search="products categories" class="fa fa-search" style="color:black;"> </i> </button>
            </div>
        </div>
        <br>
    </div>

    <div class="row">

        <div class="col-md-3" style="border-right: 1px solid #eef;min-height:500px;">
            <p class="lead">Categories</p>
            <div class="list-group datalist" data-resource-holder="categories">
            </div>
            <div data-resource-template="categories">
                <a onclick="rmdSearchByValue('{{name}}');" class="list-group-item">{{name}}</a>
            </div>
        </div>

        <div class="col-md-9" style="border-right: 1px solid #eef;min-height:500px;">
            <p class="lead">Products</p>
            <div class="row datalist" data-resource-holder="products">
            </div>

            <div data-resource-template="products">
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <div class="caption">
                            <h5><a data-resource="products" data-id="{{id}}" target="_blank" href="/products/{{id}}">{{name}}</a></h5>
                            <h5>SGD {{price}}</h5>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- /.container -->

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>